// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	 int ntimes = Integer.parseInt( args[0]);
	 int i = 0;
	 int indexmore = 0;
	 int indexless = 0;
	 while (  i < ntimes) {
     double half = Math.random();
		if (half > 0.5){
		 indexmore ++;
		}
		else{
		 indexless ++;
		}
		i++;
	 }
	 System.out.println(">0.5: " + indexmore + " times");
	 System.out.println("<=0.5: " + indexless + " times");
	 if( indexless > 0){
		double ratio = (double) indexmore / indexless ;
		System.out.println( "Ratio: " + ratio);

	 }
	 
	}
}
